interface ICategoryTag {
    key: string,
    category: string[]
}

export const categoryTags : ICategoryTag[] =  [
    {
        key: 'Accessories',
        category: [
            'jewelry',
            'watches',
            'sunglasses',
            'handbags',
            'wallets',
            'belts',
            'hats',
            'scarves',
            'gloves',
            'hair accessories',
            'ties',
            'bow ties',
            'socks',
            'leggings',
            'stockings',
            'tights',
            'umbrellas',
            'keychains',
            'phone cases',
            'headphones',
            'earphones',
            'earrings',
            'necklaces',
            'bracelets',
            'rings',
            'brooches',
            'pins',
            'watches',
            'watch bands',
            'sunglasses',
            'eyeglasses',
            'reading glasses',
            'prescription glasses',
            'handbags',
            'tote bags',
            'clutches',
            'crossbody bags',
            'backpacks',
            'shoulder bags',
            'wallets',
            'card holders',
            'coin purses',
            'belts',
            'waist belts',
            'hip belts',
            'hats',
            'caps',
            'beanies',
            'fedoras',
            'sun hats',
            'visors',
            'scarves',
            'wool scarves',
            'cashmere scarves',
            'silk scarves',
            'cotton scarves',
            'gloves',
            'leather gloves',
            'wool gloves',
            'cashmere gloves',
            'fingerless gloves',
            'hair accessories',
            'hair clips',
            'hair bands',
            'hair ties',
            'headbands',
            'ties',
            'bow ties',
            'silk ties',
            'cotton ties',
            'wool ties',
            'socks',
            'ankle socks',
            'crew socks',
            'knee-high socks',
            'thigh-high socks',
            'leggings',
            'patterned leggings',
            'printed leggings',
            'athletic leggings',
            'stockings',
            'fishnet stockings',
            'lace stockings',
            'opaque stockings',
            'tights',
            'patterned tights',
            'opaque tights',
            'sheer tights',
            'umbrellas',
            'compact umbrellas',
            'bubble umbrellas',
            'transparent umbrellas',
            'keychains',
            'keyrings',
            'phone cases',
            'phone wallets',
            'phone grips',
            'headphones',
            'earphones',
            'Bluetooth headphones',
            'wireless earphones',
            'backpacks',
            'tote bags',
            'briefcases',
            'socks',
            'ties',
            'umbrellas',
            'hair accessories',
            'eyewear',
            'handkerchiefs',
            'caps',
            'beanies',
            'glasses',
            'purses',
            'clutches',
            'earrings',
            'necklaces',
            'bracelets',
            'rings',
            'cufflinks',
            'bow ties',
            'keychains',
            'phone cases',
            'luggage',
            'travel accessories',
            'scarf',
            'gloves',
            // 'Europe',
            'North America',
            // Accessory brands in EU
            'Louis Vuitton',
            'Gucci',
            'Hermes',
            'Chanel',
            'Prada',
            'Dior',
            'Burberry',
            'Fendi',
            'Valentino',
            'Balenciaga',
            'Celine',
            'Givenchy',
            'Yves Saint Laurent',
            'Alexander McQueen',
            'Loewe',
            'Bottega Veneta',
            'Miu Miu',
            'Versace',
            'Jimmy Choo',
            'Kenzo',
            'Moschino',
            'Off-White',
            'Rimowa',
            'Longchamp',
            'Maison Margiela',
            'Bally',
            // Accessory brands in North America
            'Michael Kors',
            'Coach',
            'Kate Spade',
            'Tory Burch',
            'Marc Jacobs',
            'Calvin Klein',
            'Ralph Lauren',
            'Tommy Hilfiger',
            'Vera Bradley',
            'Fossil',
            'Guess',
            'Dooney & Bourke',
            'Cole Haan',
            'Rebecca Minkoff',
            'Nordstrom',
            'Saks Fifth Avenue',
            'GAP',
            'Banana Republic',
            'J.Crew',
            'Lululemon',
            'Under Armour',
            'The North Face',
            'Patagonia',
            'Columbia',
            'Oakley',
            'Ray-Ban',
            'Nixon',
            'Timex',
            'Casio',
            'Vans',
            'Converse',
            'New Era',
        ]
    },
    {
        key: "Arts & Crafts",
        category:  [
            'paint',
            'canvas',
            'brushes',
            'sketchbooks',
            'colored pencils',
            'markers',
            'watercolor',
            'acrylic paint',
            'oil paint',
            'charcoal',
            'pastels',
            'drawing pens',
            'craft paper',
            'scissors',
            'glue',
            'craft paint',
            'glitter',
            'craft foam',
            'beads',
            'embroidery floss',
            'sewing machine',
            'yarn',
            'knitting needles',
            'crochet hooks',
            'felt',
            'ribbons',
            'buttons',
            'sequins',
            'pom poms',
            'stencils',
            'wooden craft sticks',
            'paper plates',
            'pipe cleaners',
            'googly eyes',
            'feathers',
            'modeling clay',
            'origami paper',
            'paper punches',
            'paper clips',
            'rubber stamps',
            'ink pads',
            'ribbon bows',
            'cotton balls',
            'paper bags',
            'glue gun',
            'rhinestones',
            'jewelry findings',
            'craft wire',
            'adhesive tape',
            'calligraphy pens',
            'heat embossing tools',
            'cutting mats',
            'quilting rulers',
            'craft storage',
            'beading thread',
            'paint palettes',
            'paintbrush holders',
            'canvas panels',
            'charcoal pencils',
            'paint markers',
            'fabric paint',
            'stitching hoops',
            'cross-stitch kits',
            'embroidery hoops',
            'knitting yarn',
            'crochet thread',
            'felting needles',
            'sewing notions',
            'quilling paper',
            'scrapbook paper',
            'sticker sheets',
            'die-cut machines',
            'punching machines',
            'embossing folders',
            'jewelry making kits',
            'beading tools',
            'craft scissors',
            'craft punches',
            'paper trimmers',
            'embroidery scissors',
            'needle felting kits',
            'sewing patterns',
            'stitch markers',
            'fabric markers',
            'quilt batting',
            'sewing thread',
            'embroidery thread',
            'knitting patterns',
            'crochet patterns',
            'quilling tools',
            'scrapbooking tools',
            'adhesive dots',
            'paper clips',
            'rubber stamp sets',
            'ink refills',
            'glitter glue',
            'sticker embellishments',
            'rhinestone stickers',
            // 'jewelry making supplies',
            'beading wire',
            'adhesive sprays',
            'calligraphy ink',
            'embossing powders',
            'stencil brushes',
        ]
    },
    {
        key: "Baby Products",
        category:  [
            'diapers',
            'baby wipes',
            'baby bottles',
            'pacifiers',
            'baby formula',
            // 'baby food',
            'baby bathtub',
            'baby shampoo',
            'baby lotion',
            'baby oil',
            'baby powder',
            'baby clothes',
            'baby onesies',
            'baby socks',
            'baby shoes',
            'baby hats',
            'baby blankets',
            'baby swaddles',
            'baby bibs',
            'baby towels',
            'baby washcloths',
            'baby carriers',
            'baby strollers',
            'baby car seats',
            'baby high chairs',
            'baby cribs',
            'baby bassinets',
            'baby changing tables',
            'baby playpens',
            'baby walkers',
            'baby bouncers',
            'baby jumpers',
            'baby toys',
            'baby rattles',
            'baby teethers',
            'baby mobiles',
            'baby activity gyms',
            'baby plush toys',
            'baby books',
            'baby monitors',
            'baby humidifiers',
            'baby thermometers',
            'baby safety gates',
            'baby outlet covers',
            'baby cabinet locks',
            'baby corner guards',
            'baby bottle sterilizers',
            'baby bottle warmers',
            'baby nasal aspirators',
            'baby nail clippers',
            'baby hairbrush',
            'baby toothbrush',
            'baby bath thermometer',
            'baby feeding spoons',
            'baby sippy cups',
            'baby food storage containers',
            'baby pacifier clips',
            'baby diaper bags',
            'baby changing pads',
            'baby nursing pillows',
            'baby bottle brushes',
            'baby bath toys',
            'baby bath seat',
            'baby bath towels',
            'baby bathrobe',
            'baby swim diapers',
            'baby sunscreen',
            'baby insect repellent',
            'baby first aid kit',
            'baby medicine dropper',
            'baby teething gel',
            'baby nasal saline solution',
            'baby laundry detergent',
            'baby hangers',
            'baby closet dividers',
            'baby drawer organizers',
            'baby diaper pail',
            'baby laundry hamper',
            'baby wet bags',
            'baby mattress',
            'baby crib sheets',
            'baby crib mobile',
            'baby crib mattress protector',
            'baby sleep sacks',
            'baby sleep sound machines',
            'baby night lights',
            'baby nursery decor',
            'baby photo frames',
            'baby milestone cards',
            'baby memory books',
            'baby diaper rash cream',
            'baby gas relief drops',
            'baby gripe water',
            'baby oral care kit',
            'baby grooming kit',
            'baby massage oil',
            'Pampers',
            'Huggies',
            'Johnson & Johnson',
            'Aveeno Baby',
            'Mustela',
            'Babyganics',
            'Burt\'s Bees Baby',
            'Seventh Generation',
            'Earth Mama',
            'Nuk',
            'Tommee Tippee',
            'Philips Avent',
            'MAM',
            'Chicco',
            'Graco',
            'Fisher-Price',
            'Skip Hop',
            'Britax',
            'Maxi-Cosi',
            'Bugaboo',
            'Stokke',
            'Medela',
            'Lansinoh',
            'Dr. Brown\'s',
            'Tula',
            'Ergobaby',
            'Aden + Anais',
            'Boppy',
            'Ingenuity',
            'Summer Infant',
            'Nuby',
            'Safety 1st',
            'Munchkin',
            'VTech',
            'Oball',
            'Playtex',
            'Evenflo',
            'NUK',
            'Disney Baby',
            'Carter\'s',
            'Gerber',
            'The Honest Company',
            'Tommy Tippee',
            'Luvable Friends',
            'Cloud Island',
            'GAP',
            'Old Navy',
            'Columbia',
            'Patagonia',
            'The North Face',
            'Ralph Lauren',
            'Gymboree',
            'OshKosh B\'gosh',
            'Zutano',
            'Robeez',
            'Stride Rite',
            'See Kai Run',
            'Livie & Luca',
            'Umi',
            'Freshly Picked',
            'Stonz',
            'Bogs',
            'KicKee Pants',
            'Tea Collection',
            'Mini Boden',
            'Janie and Jack',
            'Peek Kids',
            'Baby Bjorn',
            'Stokke',
            'Ergobaby',
            'Cybex',
            'Mamas & Papas',
            'Beaba',
            'Baby Jogger',
            'UPPAbaby',
            'Joie',
            'Silver Cross',
            'Mountain Buggy',
            'Quinny',
        ]
    },

    {
        key: 'Bags & Cases',
        category: [
            'backpacks',
            'handbags',
            'tote bags',
            'laptop bags',
            'briefcases',
            'shoulder bags',
            'crossbody bags',
            'clutches',
            'duffel bags',
            'gym bags',
            'travel bags',
            'rolling suitcases',
            'luggage sets',
            'carry-on bags',
            'garment bags',
            'camera bags',
            'diaper bags',
            'beach bags',
            'cooler bags',
            'lunch bags',
            'drawstring bags',
            'waist packs',
            'fanny packs',
            'wallets',
            'cardholders',
            'money clips',
            'passport holders',
            'keychain pouches',
            'makeup bags',
            'toiletry bags',
            'jewelry cases',
            'watch cases',
            'sunglasses cases',
            'tablet cases',
            'laptop sleeves',
            'phone cases',
            'e-reader cases',
            'camera cases',
            'document holders',
            'portfolio cases',
            'briefcase organizers',
            'gadget organizers',
            'cable organizers',
            'travel organizers',
            'cosmetic organizers',
            'jewelry organizers',
            'drawer organizers',
            'storage bins',
            'laundry bags',
            'shoe bags',
            'garment covers',
            'shopping bags',
            'reusable grocery bags',
            'trolley bags',
            'bike bags',
            'pencil cases',
            'pen holders',
            'paintbrush holders',
            'art supply organizers',
            'musical instrument cases',
            'guitar bags',
            'violin cases',
            'drum bags',
            'keyboard bags',
            // 'gun cases',
            'first aid kits',
            'tool bags',
            'toolboxes',
            'lunch containers',
            'water bottle holders',
            'wet bags',
            'fireproof document bags',
            'camera lens cases',
            'hardshell suitcases',
            'softshell suitcases',
            'rolling backpacks',
            'laptop backpacks',
            'camera backpacks',
            'diaper backpacks',
            'trolley backpacks',
            'rolling duffel bags',
            'cooler backpacks',
            'toiletry travel kits',
            'travel jewelry cases',
            'travel shoe bags',
            'travel garment bags',
            'travel document wallets',
            'travel cosmetic bags',
            'travel toiletry organizers',
            'Coach',
            'Michael Kors',
            'Kate Spade',
            'Tory Burch',
            'Marc Jacobs',
            'Ralph Lauren',
            'Calvin Klein',
            'Tommy Hilfiger',
            'Cole Haan',
            'Dooney & Bourke',
            'Rebecca Minkoff',
            'Ted Baker',
            'Fossil',
            'Kipling',
            'Herschel Supply Co.',
            'Tumi',
            'Samsonite',
            'Rimowa',
            'Eastpak',
            'American Tourister',
            'JanSport',
            'Timbuk2',
            'Filson',
            'Hedgren',
            'Kipling',
            'Knomo',
            'Lipault',
            'Matt & Nat',
            'Pacsafe',
            'Victorinox',
            'Away',
            'Briggs & Riley',
            'Eagle Creek',
            'Hartmann',
            'Travelpro',
        ]
    },
    {
        key: 'Cleaning Supplies',
        category: [
            'all-purpose cleaners',
            'bathroom cleaners',
            'kitchen cleaners',
            'floor cleaners',
            'window cleaners',
            'disinfectant wipes',
            'disinfectant sprays',
            'toilet cleaners',
            'glass cleaners',
            'stain removers',
            'carpet cleaners',
            'furniture polish',
            'wood cleaners',
            'stainless steel cleaners',
            'granite cleaners',
            'tile cleaners',
            'grout cleaners',
            'oven cleaners',
            'dish soaps',
            'dishwasher detergents',
            'laundry detergents',
            'fabric softeners',
            'bleach',
            'stain pre-treatments',
            'dryer sheets',
            'air fresheners',
            'odor eliminators',
            'mop heads',
            'broom heads',
            'dustpans',
            'sponges',
            'scrub brushes',
            'microfiber cloths',
            'latex gloves',
            'rubber gloves',
            'dishwashing gloves',
            'bucket',
            'mop',
            'broom',
            'dustpan and brush set',
            'vacuum cleaner',
            'carpet sweeper',
            'steam mop',
            'duster',
            'feather duster',
            'window squeegee',
            'toilet brush',
            'toilet plunger',
            'drying rack',
            'garbage bags',
            'trash cans',
            'trash can liners',
            'paper towels',
            'toilet paper',
            'facial tissues',
            'cleaning caddies',
            'storage containers',
            'storage baskets',
            'laundry baskets',
            'clothespins',
            'lint rollers',
            'step stool',
            'broom and mop holders',
            'vacuum cleaner bags',
            'vacuum cleaner filters',
            'cleaning gloves',
            'cleaning aprons',
            'cleaning masks',
            'dust masks',
            'mop buckets',
            'spray bottles',
            'extension poles',
            'dust masks',
            'cleaning brushes',
            'oven mitts',
            'dish drying mats',
            'cleaning cloths',
            'dust cloths',
            'cleaning solution refills',
            'spot cleaners',
            'pet stain removers',
            'grout brushes',
            'carpet deodorizers',
            'fabric refreshers',
            'air purifiers',
            'vacuum cleaner attachments',
            'dryer vent brushes',
            'duster refills',
            'broom handles',
            'cleaning wipes',
            'window cleaning kits',
            'microfiber mop pads',
            'squeegee handles',
            'mop refill pads',
            'mop and broom holders',
            'cleaning trolleys',
            'floor polishers',
        ]
    },
    {
        key: 'DIY & Tools',
        category: [
            'power tools',
            'hand tools',
            'screwdrivers',
            'wrenches',
            'pliers',
            'hammers',
            'saws',
            'drills',
            'grinders',
            'sanders',
            'nail guns',
            'staple guns',
            'measuring tools',
            'tape measures',
            'levels',
            'squares',
            'rulers',
            'marking tools',
            'chisels',
            'files',
            'scrapers',
            'knives',
            'cutting tools',
            'soldering',
            'welding',
            'gluing',
            'adhesives',
            'fasteners',
            'screws',
            'nails',
            'nuts and bolts',
            'anchors',
            'hooks',
            'brackets',
            'clamps',
            'vices',
            'ladders',
            'step stools',
            'workbenches',
            'storage',
            'toolboxes',
            'tool bags',
            'organizers',
            'workshop',
            'workshop equipment',
            'workshop supplies',
            'safety equipment',
            'gloves',
            'protective eyewear',
            'masks',
            'ear protection',
            'workwear',
            'aprons',
            'painting',
            'paint brushes',
            'rollers',
            'paint trays',
            'paint sprayers',
            'sandpaper',
            'paints',
            'stains',
            // 'varnishes',
            'sealants',
            'fillers',
            'caulking',
            'plumbing',
            'pipes',
            'fittings',
            'valves',
            'faucets',
            'plungers',
            'drain snakes',
            'electrical',
            'wiring',
            'outlets',
            'switches',
            'circuit breakers',
            'extension cords',
            'lighting',
            'bulbs',
            'fixtures',
            'ceiling fans',
            'home automation',
            'smart home',
            'security systems',
            'door locks',
            'doorbells',
            'thermostats',
            'home improvement',
            'renovation',
            'remodeling',
            'construction',
            'carpentry',
            'woodworking',
            'metalworking',
            'masonry',
            'tiling',
            'flooring',
            'plastering',
            'drywall',
            'insulation',
            'roofing',
            'fencing',
            'decking',
            'gates',
            'landscaping',
            'gardening',
            'planting',
            'pruning',
            'trimming',
            'irrigation',
            'garden tools',
            'greenhouse',
            'DIY projects',
            'home repairs',
            'home maintenance',
            'tool sets',
            'home renovation books',
            'DIY tutorials',
            'how-to guides',
            'DIY workshops',
            'tool rentals',
        ]
    },
    {
        key: 'Electronics',
        category: [
            'smartphones',
            'laptops',
            'tablets',
            'headphones',
            'speakers',
            'televisions',
            'cameras',
            'gaming consoles',
            'smartwatches',
            'fitness trackers',
            'printers',
            'monitors',
            'keyboards',
            'mice',
            'hard drives',
            'routers',
            'modems',
            'memory cards',
            'USB drives',
            'batteries',
            'chargers',
            'cables',
            'adapters',
            'power banks',
            'smart home devices',
            'virtual reality headsets',
            'drones',
            'robotic vacuum cleaners',
            'smart thermostats',
            'smart locks',
            'smart lighting',
            'smart plugs',
            'action cameras',
            'portable speakers',
            'wireless earphones',
            'bluetooth headphones',
            'gaming accessories',
            'gaming keyboards',
            'gaming mice',
            'gaming headsets',
            'gaming monitors',
            'gaming chairs',
            'car electronics',
            'car stereos',
            'car speakers',
            'car amplifiers',
            'car GPS',
            'car dash cameras',
            'car phone holders',
            'home theater systems',
            'soundbars',
            'projectors',
            'DVD players',
            'blu-ray players',
            'media streaming devices',
            'smart TVs',
            'sound systems',
            'digital cameras',
            'mirrorless cameras',
            'DSLR cameras',
            'instant cameras',
            'point-and-shoot cameras',
            'camera lenses',
            'camera tripods',
            'camera bags',
            'camera accessories',
            'lenses',
            'camera filters',
            'camera flashes',
            'memory card readers',
            'camera cleaning kits',
            'gaming laptops',
            'ultrabooks',
            '2-in-1 laptops',
            'gaming desktops',
            'all-in-one computers',
            'computer components',
            'processors',
            'graphics cards',
            'motherboards',
            'RAM',
            'SSDs',
            'HDDs',
            'computer cases',
            'power supplies',
            'computer cooling',
            'computer peripherals',
            'printers',
            'scanners',
            'projectors',
            'monitors',
            'keyboards',
            'mice',
            'webcams',
            'speakers',
            'headsets',
            'microphones',
            'drawing tablets',
            'graphics tablets',
            'stylus pens',
            'smartphones accessories',
            'phone cases',
            'screen protectors',
            'charging cables',
            'car mounts',
            'wireless chargers',
            'phone grips',
            'headphone adapters',
            'smartphone lenses',
            'selfie sticks',
            'mobile power banks',
            'tablets accessories',
            'tablet cases',
            'screen protectors',
            'stylus pens',
            'tablet keyboards',
            'tablet stands',
            'tablet mounts',
            'wireless speakers',
            'earphones',
            'over-ear headphones',
            'noise-cancelling headphones',
            'gaming headsets',
            'wireless headphones',
            'bluetooth speakers',
            'home speakers',
            'portable speakers',
            'electronics',
            'technology',
            'gadgets',
            'smartphones',
            'computers',
            'laptops',
            'televisions',
            'headphones',
            'speakers',
            'cameras',
            'Apple',
            'Samsung',
            'Sony',
            'LG',
            'Panasonic',
            'Philips',
            'Bose',
            'JBL',
            'Beats',
            'Dell',
            'HP',
            'Lenovo',
            'Microsoft',
            'ASUS',
            'Acer',
            'Canon',
            'Nikon',
            'GoPro',
            'Fujifilm',
            'Huawei',
            'Xiaomi',
            'OnePlus',
            'Motorola',
            'Nokia',
            'Google',
            // 'Amazon',
            'Fitbit',
            'Garmin',
            'Sonos',
            'Bang & Olufsen',
            'Braun',
            'Siemens',
            'Bosch',
            'Sharp',
            'Toshiba',
            'AEG',
            'Electrolux',
            'Miele',
            'Whirlpool',
            'Kenwood',
            'Zanussi',
            'Grundig',
            'Honeywell',
            'Black & Decker',
            'DeWalt',
            'Razer',
            'Corsair',
            'Logitech',
            'Sennheiser',
            'AKG',
            'Marshall',
            'Pioneer',
            'Yamaha',
            'Denon',
            'Onkyo',
            'Harman Kardon',
            'Philips Hue',
            'Epson',
            'Brother',
            'Dyson',
            'Neato',
            'Miele',
            'iRobot',
            'Vizio',
            'Roku',
            'Nest',
            'Ring',
            'August',
        ]
    },
    {
        key: 'Footwear',
        category: [
            'sneakers',
            'running shoes',
            'athletic shoes',
            'sports shoes',
            'tennis shoes',
            'basketball shoes',
            'soccer shoes',
            'football shoes',
            'cleats',
            'hiking boots',
            'work boots',
            'winter boots',
            'rain boots',
            'sandals',
            'flip-flops',
            'slippers',
            'dress shoes',
            'loafers',
            'oxfords',
            'brogues',
            'derby shoes',
            'pumps',
            'heels',
            'wedges',
            'flats',
            'ballerina shoes',
            'moccasins',
            'boots',
            'ankle boots',
            'knee-high boots',
            'over-the-knee boots',
            'chelsea boots',
            'combat boots',
            'riding boots',
            'workout shoes',
            'gym shoes',
            'training shoes',
            'skate shoes',
            'skateboarding shoes',
            'slip-on shoes',
            'canvas shoes',
            'espadrilles',
            'platform shoes',
            'slingback shoes',
            'mary jane shoes',
            'boat shoes',
            'mules',
            'clogs',
            'safety shoes',
            'steel toe shoes',
            'water shoes',
            'dance shoes',
            'tap shoes',
            'ballet shoes',
            'jazz shoes',
            'character shoes',
            'cheerleading shoes',
            'golf shoes',
            'bowling shoes',
            'cycling shoes',
            'climbing shoes',
            'weightlifting shoes',
            'barefoot shoes',
            'diabetic shoes',
            'orthopedic shoes',
            'wide width shoes',
            'narrow width shoes',
            'extra cushioned shoes',
            'memory foam shoes',
            'arch support shoes',
            'plantar fasciitis shoes',
            'shoe accessories',
            'shoe care',
            'shoe polish',
            'shoe cleaner',
            'shoe laces',
            'shoe insoles',
            'shoe inserts',
            'shoe bags',
            'shoe organizers',
            'shoe racks',
            'shoe shelves',
            'shoe storage',
            'shoe repair',
            'shoe stretching',
            'shoe waterproofing',
            'Alden',
            'Allen Edmonds',
            'Balenciaga',
            'Bally',
            'Berluti',
            'Birkenstock',
            'Bottega Veneta',
            'Buscemi',
            'Church\'s',
            'Clarks',
            'Cole Haan',
            'Common Projects',
            'Crocs',
            'Diadora',
            'Dior',
            'Dr. Martens',
            'Fila',
            'Filling Pieces',
            'Gucci',
            'Hoka One One',
            'J.Crew',
            'Jimmy Choo',
            'Lacoste',
            'Le Coq Sportif',
            'Loewe',
            'Magnanni',
            'Maison Margiela',
            'Merrell',
            'Mephisto',
            'Miu Miu',
            'Moncler',
            'Onitsuka Tiger',
            'Oofos',
            'Paul Smith',
            'Prada',
            'Red Wing Shoes',
            'Rick Owens',
            'Rothy\'s',
            'Saint Laurent',
            'Salvatore Ferragamo',
            'Santoni',
            'Skechers',
            'Sperry',
            'Steve Madden',
            'Stuart Weitzman',
            'Superga',
            'Tod\'s',
            'Timberland',
            'Tommy Hilfiger',
            'Ugg',
            'Valentino',
            'Veja',
            'Versace',
            'Y-3',
            'Yeezy',
            'Zara',
            'Zegna',
        ]
    },
    {
        key: 'Jewelry',
        category: [
            'necklaces',
            'pendants',
            'chains',
            'chokers',
            'bracelets',
            'bangles',
            'cufflinks',
            'rings',
            'earrings',
            'hoop earrings',
            'stud earrings',
            'dangle earrings',
            'drop earrings',
            'ear cuffs',
            'anklets',
            'brooches',
            'pins',
            'gold',
            'charms',
            'lockets',
            'birthstone jewellery',
            'pearl jewellery',
            'diamond jewellery',
            'gemstone jewellery',
            'gold jewellery',
            'silver jewellery',
            'platinum jewellery',
            'rose gold jewellery',
            'vintage jewellery',
            'fashion jewellery',
            'statement jewellery',
            'bridal jewellery',
            'wedding rings',
            'engagement rings',
            'promise rings',
            'anniversary rings',
            'cocktail rings',
            'stackable rings',
            'toe rings',
            'jewellery sets',
            'jewellery boxes',
            'jewellery organizers',
            'watch bands',
            'watch accessories',
            'bracelet watches',
            'dress watches',
            'chronograph watches',
            'automatic watches',
            'smartwatches',
            'fob watches',
            'pocket watches',
            'tie clips',
            'money clips',
            'keychains',
            'jewellery cleaning kits',
            'jewellery polish',
            'jewellery storage',
            'jewellery display',
            'body jewellery',
            'nose rings',
            'lip rings',
            'eyebrow rings',
            'belly button rings',
            'nipple rings',
            'tongue rings',
            'captured bead rings',
            'body chains',
            'ankle bracelets',
            'jewellery for men',
            'jewellery for women',
            'jewellery for kids',
            'personalized jewellery',
            'initial jewellery',
            'name necklaces',
            'monogram jewellery',
            'birthstone jewellery',
            'engraved jewellery',
            'handmade jewellery',
            'beaded jewellery',
            'wire wrapped jewellery',
            'resin jewellery',
            'leather jewellery',
            'wooden jewellery',
            'shell jewellery',
            'boho jewellery',
            'ethnic jewellery',
            'tribal jewellery',
            'statement necklaces',
            'chunky necklaces',
            'layered necklaces',
            'chandelier earrings',
            'tassel earrings',
            'statement bracelets',
            'cuff bracelets',
            'layered bracelets',
            'statement rings',
            'cocktail rings',
            'stacking rings',
            'statement brooches',
            'vintage brooches',
            'pin brooches',
            'jewellery repair',
            'jewellery resizing',
            'jewellery cleaning',
            'jewellery maintenance',
            'Brooches',
            'Tiffany & Co.',
            'Cartier',
            'Bulgari',
            'Chopard',
            'Van Cleef & Arpels',
            'Graff',
            'Harry Winston',
            'Piaget',
            'Boucheron',
            'Mikimoto',
            'David Yurman',
            'Pomellato',
            'Chaumet',
            'Swatch',
            'Patek Philippe',
            'Rolex',
            'Omega',
            'Tag Heuer',
            'Chanel',
            'Hermès',
            'Dior',
            'Louis Vuitton',
            'Gucci',
            'Bvlgari',
            'Prada',
            'Versace',
            'Yves Saint Laurent',
            'Givenchy',
            'Celine',
            'Alexander McQueen',
            'Bottega Veneta',
            'Fendi',
            'Balenciaga',
            'Valentino',
            'LVMH',
            'Swarovski',
            'Swarovski Jewelry',
            'Swarovski Crystals',
            'Swarovski Elements',
            'Swarovski Gemstones',
            'Pandora',
            'Pandora Jewelry',
            'Links of London',
            'Swarovski Atelier',
            'Swarovski Optik',
            'Thomas Sabo',
            'Chopard Jewelry',
            'Chopard Watches',
            'Bulgari Jewelry',
            'Bulgari Watches',
            'Cartier Jewelry',
            'Cartier Watches',
            'Piaget Jewelry',
            'Piaget Watches',
            'Graff Jewelry',
            'Graff Watches',
            'Harry Winston Jewelry',
            'Harry Winston Watches',
        ]
    },
    {
        key: 'Media',
        category:  [
            'books',
            'eBooks',
            'audiobooks',
            'magazines',
            'newspapers',
            'comics',
            'graphic novels',
            'music',
            'albums',
            'singles',
            'vinyl records',
            'CDs',
            'cassettes',
            'digital music',
            'movies',
            'DVDs',
            'Blu-rays',
            '4K Ultra HD',
            'digital movies',
            'TV shows',
            'box sets',
            'streaming media',
            'video games',
            'console games',
            'PC games',
            'Nintendo Switch games',
            'PlayStation games',
            'Xbox games',
            'VR games',
            'mobile games',
            'board games',
            'card games',
            'puzzles',
            'educational media',
            'documentaries',
            'educational books',
            'educational apps',
            'art supplies',
            'painting',
            'drawing',
            'sketching',
            'crafting',
            'sculpting',
            'photography',
            'editing software',
            'printing services',
            'musical instruments',
            'guitars',
            'pianos',
            'drums',
            'violin',
            'flute',
            'trumpet',
            'saxophone',
            'microphones',
            'audio equipment',
            'studio recording',
            'music lessons',
            'dance',
            'ballet',
            'hip hop',
            'salsa',
            'tango',
            'tap',
            'theater',
            'plays',
            'musicals',
            'tickets',
            'concerts',
            'live events',
            'sports',
            'sporting events',
            'fitness',
            'workout videos',
            'exercise equipment',
            'yoga',
            'meditation',
            'cooking',
            'cookbooks',
            'recipes',
            'cooking shows',
            'culinary classes',
            'travel',
            'travel books',
            'travel guides',
            'travel documentaries',
            'language learning',
            'language courses',
            'language apps',
            'self-help',
            'inspirational books',
            'motivational speakers',
            'personal development',
            'productivity',
            'business',
            'entrepreneurship',
            'finance',
            'investing',
            'economics',
            'technology',
            'science',
            'nature',
            'environment',
            'history',
            'biographies',
            'autobiographies',
            'true crime',
            'fiction',
            'fantasy',
            'science fiction',
            'mystery',
            'romance',
            'thriller',
            'horror',
            'poetry',
            'literary classics',
            'children\'s books',
            'young adult',
            'comic books',
            'graphic novels',
            'music documentaries',
            'film documentaries',
            'video game documentaries',
            'art documentaries',
            'educational documentaries',
            'sports documentaries',
            'nature documentaries',
            'travel documentaries',
            'historical documentaries',
            'science documentaries',
        ]
    },
    {
        key: 'Music',
        category:[
            'rock',
            'pop',
            'hip hop',
            'rap',
            // 'country',
            'alternative',
            'indie',
            'electronic',
            'dance',
            'r&b',
            'soul',
            'jazz',
            'blues',
            'reggae',
            'classical',
            'folk',
            'punk',
            'metal',
            'instrumental',
            'world music',
            'latin',
            'k-pop',
            'j-pop',
            'gospel',
            'christian',
            'soundtracks',
            'compilations',
            'live recordings',
            'remixes',
            'acoustic',
            'covers',
            'original songs',
            'singer-songwriter',
            'boy bands',
            'girl groups',
            'duets',
            'solo artists',
            'music festivals',
            'concerts',
            'live performances',
            'music videos',
            'music streaming',
            'online music stores',
            'music production',
            'recording studios',
            'music equipment',
            'musical instruments',
            'music lessons',
            'sheet music',
            'music theory',
            'music notation',
            'music software',
            'music apps',
            'music events',
            'music industry',
            'music news',
            'music reviews',
            'music charts',
            'music awards',
            'music documentaries',
            'music history',
            'music genres',
            'music trivia',
            'music merch',
            'vinyl records',
            'CDs',
            'digital music',
            'music playlists',
            'music recommendations',
            'music blogs',
            'music podcasts',
            'music communities',
            'music forums',
            'music social media',
            'music education',
            'music therapy',
            'music research',
            'music careers',
            'music marketing',
            'music licensing',
            'music copyright',
            'music royalties',
            'music contracts',
        ]
    },
    {
        key: 'Occasion',
        category:[
            'birthday',
            'anniversary',
            'wedding',
            'engagement',
            'graduation',
            'retirement',
            'promotion',
            'baby shower',
            'bridal shower',
            'housewarming',
            'new job',
            'farewell',
            'get well soon',
            'thank you',
            'congratulations',
            'sympathy',
            'condolence',
            'thinking of you',
            'sorry',
            'apology',
            'love',
            'friendship',
            'just because',
            'holiday',
            'Christmas',
            'Easter',
            'Thanksgiving',
            'Valentine\'s Day',
            'Mother\'s Day',
            'Father\'s Day',
            'Halloween',
            'New Year',
            'Independence Day',
            'Hanukkah',
            'Kwanzaa',
            'religious',
            'religious ceremonies',
            'religious holidays',
            'religious events',
            'religious milestones',
            'religious celebrations',
            'graduation party',
            'wedding party',
            'baby shower party',
            'bridal shower party',
            'engagement party',
            'retirement party',
            'promotion party',
            'farewell party',
            'welcome party',
            'surprise party',
            'cocktail party',
            'dinner party',
            'tea party',
            'BBQ party',
            'picnic party',
            'pool party',
            'beach party',
            'garden party',
            'themed party',
            'costume party',
            'masquerade party',
            'casual party',
            'formal party',
            'outdoor party',
            'indoor party',
            'family gathering',
            'reunion',
            'office party',
            'corporate event',
            'charity event',
            'fundraising event',
            'business conference',
            'seminar',
            'workshop',
            'trade show',
            'product launch',
            'networking event',
            'awards ceremony',
            'art exhibition',
            'concert',
            'theater performance',
            'dance performance',
            'sports event',
            'sporting competition',
            'movie premiere',
            'film festival',
            'book signing',
            'literary event',
            'fashion show',
            'gala dinner',
            'black-tie event',
            'red carpet event',
            'VIP event',
            'private event',
            'public event',
            'celebration',
            'festivity',
            'commemoration',
            'ceremony',
            'ritual',
            'memorial',
            'tribute',
            'gathering',
            'party',
            'halloween',
            'event planning',
            'event coordination',
            'event management',
            'event decorations',
            'event invitations',
            'event catering',
            'event rentals',
            'event entertainment',
            'event photography',
            'event videography',
            // 'event marketing',
            // 'event promotion',
            'flowers',
            'flower',
            'event tickets',
        ]
    },
    {
        key: 'Outdoor Living',
        category:[
            'patio furniture',
            'outdoor sofas',
            'outdoor sectionals',
            'outdoor dining sets',
            'outdoor tables',
            'outdoor chairs',
            'outdoor benches',
            'outdoor loungers',
            'hammocks',
            'porch swings',
            'outdoor umbrellas',
            'outdoor cushions',
            'patio heaters',
            'fire pits',
            'outdoor lighting',
            'outdoor rugs',
            'outdoor decor',
            'outdoor planters',
            'outdoor fountains',
            'outdoor statues',
            'outdoor wall art',
            'grills',
            'outdoor cooking equipment',
            'outdoor dinnerware',
            'picnic baskets',
            'coolers',
            'outdoor storage',
            'deck boxes',
            'storage benches',
            'outdoor sheds',
            'gardening tools',
            'plant pots',
            'garden hoses',
            'watering cans',
            'gardening gloves',
            'gardening accessories',
            'outdoor games',
            'badminton sets',
            'cornhole sets',
            'croquet sets',
            'bocce ball sets',
            'lawn darts',
            'outdoor sports equipment',
            'bikes',
            'skateboards',
            'rollerblades',
            'scooters',
            'trampolines',
            'outdoor toys',
            'playhouses',
            'swing sets',
            'sandbox',
            'water slides',
            'outdoor pet supplies',
            'dog houses',
            'cat houses',
            'birdhouses',
            'outdoor pest control',
            'insect repellents',
            'bug zappers',
            'outdoor cleaning supplies',
            'pressure washers',
            'outdoor brooms',
            'outdoor storage covers',
            'outdoor furniture covers',
            'grill covers',
            'patio umbrella covers',
            'fire pit covers',
            'outdoor equipment covers',
            'outdoor safety',
            'outdoor first aid kits',
            'sunscreen',
            'bug sprays',
            'emergency whistles',
            'outdoor apparel',
            'hats',
            'sunglasses',
            'sun hats',
            'outdoor footwear',
            'hiking boots',
            'sandals',
            'water shoes',
            'outdoor clothing',
            'rain jackets',
            'windbreakers',
            'hiking pants',
            'outdoor accessories',
            'backpacks',
            'water bottles',
            'camping gear',
            'sleeping bags',
            'camping tents',
            'camping chairs',
            'camping stoves',
            'camping lanterns',
            'camping cookware',
            'camping utensils',
            'camping hammocks',
            'camping tarps',
        ]
    },
    {
        key: 'Personal Care',
        category:[
            'skincare',
            'cleansers',
            'moisturizers',
            'serums',
            'face masks',
            'facial scrubs',
            'toners',
            'essences',
            'eye creams',
            'lip care',
            'sunscreen',
            'body care',
            'body wash',
            'body lotion',
            'body oil',
            'body butter',
            'hand cream',
            'foot care',
            'shower gel',
            'bath bombs',
            'bath salts',
            'deodorant',
            'antiperspirant',
            'hair care',
            'shampoo',
            'conditioner',
            'hair mask',
            'hair oil',
            'hair serum',
            'hair spray',
            'hair gel',
            'hair wax',
            'styling tools',
            'hairbrushes',
            'combs',
            'hairdryers',
            'curling irons',
            'straighteners',
            'electric shavers',
            'razors',
            'shaving cream',
            'aftershave',
            'beard care',
            'fragrances',
            'perfumes',
            'colognes',
            'body mists',
            'essential oils',
            'oral care',
            'toothpaste',
            'toothbrushes',
            'mouthwash',
            'dental floss',
            'lip balm',
            'feminine care',
            'sanitary pads',
            'tampons',
            'menstrual cups',
            'body wash',
            'shaving cream',
            'waxing',
            'nail care',
            'nail polish',
            'nail polish remover',
            'nail tools',
            'manicure sets',
            'pedicure sets',
            'foot files',
            'callus removers',
            'massage',
            'massage oils',
            'massage tools',
            'medicines',
            'pain relievers',
            'fever reducers',
            'cough syrup',
            'allergy medication',
            'vitamins',
            'supplements',
            'weight management',
            'dietary aids',
            'sleep aids',
            'eye care',
            'contact lenses',
            'contact lens solution',
            'eye drops',
            'eye masks',
            'first aid',
            'band-aids',
            'antiseptics',
            // 'bandages',
            'hot\/cold packs',
            'medical equipment',
            'thermometers',
            'blood pressure monitors',
            'personal care accessories',
            'mirrors',
            'toiletry bags',
            'travel kits',
            'cosmetic cases',
            'makeup brushes',
            'makeup sponges',
            'cosmetic organizers',
            'shower caps',
            'bath accessories',
            'toilet paper',
            'tissues',
            'cotton pads',
            'cotton swabs',
            'wet wipes',
        ]
    },
    {
        key: 'Pet Supplies',
        category: [
            'dog food',
            'cat food',
            'dog treats',
            'cat treats',
            'dog toys',
            'cat toys',
            'dog bed',
            'cat bed',
            'dog collar',
            'cat collar',
            'dog leash',
            'cat leash',
            'dog grooming',
            'cat grooming',
            'dog shampoo',
            'cat shampoo',
            'dog bowl',
            'cat bowl',
            'dog crate',
            'cat crate',
            'dog carrier',
            'cat carrier',
            'dog harness',
            'cat harness',
            'dog training pads',
            'cat litter',
            'cat litter box',
            'cat scratching post',
            'bird cage',
            'fish tank',
            'hamster cage',
            'rabbit hutch',
            'guinea pig cage',
            'reptile terrarium',
            'small animal bedding',
            'bird food',
            'fish food',
            'hamster food',
            'rabbit food',
            'guinea pig food',
            'reptile food',
            'bird toys',
            'fish tank decorations',
            'hamster wheel',
            'rabbit hay',
            'guinea pig hay',
            'reptile heat lamp',
            'small animal water bottle',
            'bird cage accessories',
            'fish tank filter',
            'hamster bedding',
            'rabbit litter',
            'guinea pig bedding',
            'reptile substrate',
            'small animal treats',
            'bird cage perches',
            'fish tank air pump',
            'hamster exercise ball',
            'rabbit toys',
            'guinea pig toys',
            'reptile hiding cave',
            'small animal hay rack',
            'bird cages covers',
            'fish tank heater',
            'hamster hideout',
            'rabbit water bottle',
            'guinea pig water bottle',
            'reptile UVB light',
            'small animal nail clippers',
            'bird nest boxes',
            'fish tank thermometer',
            'hamster chew toys',
            'rabbit litter box',
            'guinea pig litter box',
            'reptile basking spot',
            'small animal litter',
            'bird bath',
            'fish tank gravel',
            'hamster exercise wheel',
            'rabbit litter scoop',
            'guinea pig hay rack',
            'reptile water dish',
            'small animal playpen',
            'bird perches',
            'fish tank light',
            'hamster water bottle',
            'rabbit litter pan',
            'guinea pig litter pan',
            'reptile humidity gauge',
            'small animal tunnel',
            'bird toys with bells',
            'fish tank background',
            'hamster ball',
            'rabbit litter tray',
            'guinea pig litter tray',
            'reptile thermostat',
            'small animal hut',
            'bird food dishes',
            'fish tank plants',
            'hamster bedding material',
            'rabbit litter mat',
            'guinea pig litter mat',
            'reptile feeding dish',
            'small animal exercise ball',
        ]
    },
    {
        key: 'Sporting Goods',
        category: [
            'football',
            'soccer',
            'basketball',
            'baseball',
            'softball',
            'volleyball',
            'tennis',
            'golf',
            'hockey',
            'lacrosse',
            'rugby',
            'cricket',
            'badminton',
            'table tennis',
            'swimming',
            'diving',
            'water polo',
            'surfing',
            'skateboarding',
            'roller skating',
            'ice skating',
            'skiing',
            'snowboarding',
            'cross-country skiing',
            'snowshoeing',
            'hiking',
            'camping',
            'climbing',
            'bouldering',
            'mountaineering',
            'cycling',
            'road biking',
            'mountain biking',
            'bmx',
            'running',
            'jogging',
            'trail running',
            'marathon',
            'triathlon',
            'fitness',
            'exercise',
            'weightlifting',
            'strength training',
            'yoga',
            'pilates',
            'aerobics',
            'cardio',
            'jump rope',
            'boxing',
            'martial arts',
            'wrestling',
            'gymnastics',
            'dancing',
            'skipping rope',
            'exercise equipment',
            'treadmill',
            'exercise bike',
            'elliptical trainer',
            'rowing machine',
            'weight bench',
            'dumbbells',
            'kettlebells',
            'resistance bands',
            'medicine balls',
            'fitness trackers',
            'sports apparel',
            'jerseys',
            'shorts',
            't-shirts',
            'tank tops',
            'hoodies',
            'jackets',
            'leggings',
            'sports bras',
            'socks',
            'shoes',
            'cleats',
            'helmets',
            'pads',
            'gloves',
            'goggles',
            'sunglasses',
            'water bottles',
            'backpacks',
            'duffel bags',
            'sports bags',
            'equipment bags',
            'coaching',
            'training',
            'sports medicine',
            'first aid',
            'sports nutrition',
            'hydration',
            'recovery',
            'team sports',
            'individual sports',
            'competitive sports',
            'recreational sports',
            'outdoor sports',
            'indoor sports',
            'sporting events',
            'sports leagues',
            'sports tournaments',
            'sports camps',
            'sports clubs',
            'sports facilities',
            'sports training',
            'sports coaching',
            'sports psychology',
            'sports injuries',
            'sports recovery',
            'sports performance',
        ]
    },
    {
        key: 'Toys',
        category: [
            'action figures',
            'dolls',
            'stuffed animals',
            'building blocks',
            'puzzles',
            'board games',
            'card games',
            'educational toys',
            'STEM toys',
            'art supplies',
            'craft kits',
            'model kits',
            'remote control toys',
            'vehicles',
            'trains',
            'drones',
            'robots',
            'pretend play',
            'kitchen sets',
            'doctor kits',
            'tool sets',
            'musical instruments',
            'outdoor toys',
            'sports toys',
            'ride-on toys',
            'bikes',
            'scooters',
            'skateboards',
            'water toys',
            'pools',
            'sandboxes',
            'playhouses',
            'trampolines',
            'swing sets',
            'kites',
            'gardening toys',
            'electronic toys',
            'interactive toys',
            'virtual reality',
            'augmented reality',
            'coding toys',
            'smart toys',
            'puppets',
            'magic sets',
            'pogo sticks',
            'bounce houses',
            'balance bikes',
            'stilts',
            'juggling',
            'yo-yos',
            'marbles',
            'collectible toys',
            'action figures',
            'trading cards',
            'plush toys',
            'toy vehicles',
            'dollhouses',
            'playsets',
            'dress-up',
            'costumes',
            'make-believe',
            'party supplies',
            'birthday',
            'themed parties',
            'play tents',
            'magnetic toys',
            'puppet theaters',
            'art easels',
            'toy instruments',
            'telescopes',
            'microscopes',
            'magic tricks',
            'building sets',
            'model trains',
            'doll accessories',
            'construction toys',
            'wooden toys',
            'plastic toys',
            'metal toys',
            'foam toys',
            'puzzle toys',
            'learning toys',
            'robotics kits',
            'science kits',
            'engineering toys',
            'math toys',
            'alphabet toys',
            'counting toys',
            'memory games',
            'coordination toys',
            'problem-solving toys',
            'imaginative toys',
            'creative toys',
            'outdoor play',
            'indoor play',
            'water play',
            'sandbox play',
            'toy storage',
            'toy organization',
            'toy cleaning',
            'toy safety',
            'toy reviews',
            'toy trends',
        ]
    },
    {
        key: 'Clothing',
        category: [
            't-shirts',
            'shirts',
            'blouses',
            'tops',
            'unisex',
            'sweaters',
            'hoodies',
            'jackets',
            'coats',
            'dresses',
            'skirts',
            'pants',
            'jeans',
            'shorts',
            'leggings',
            'activewear',
            'sportswear',
            'swimwear',
            'underwear',
            'bras',
            'panties',
            'boxers',
            'briefs',
            'socks',
            'stockings',
            'tights',
            'sleepwear',
            'pajamas',
            'robes',
            'lingerie',
            'nightgowns',
            'nightwear',
            'formalwear',
            'suits',
            'blazers',
            'dress shirts',
            'dress pants',
            'ties',
            'bowties',
            'accessories',
            'belts',
            'hats',
            'caps',
            'scarves',
            'gloves',
            'sunglasses',
            'wallets',
            'handbags',
            'backpacks',
            'shoulder bags',
            'tote bags',
            'crossbody bags',
            'clutches',
            'shoes',
            'sneakers',
            'boots',
            'sandals',
            'heels',
            'flats',
            'loafers',
            'slippers',
            'formal shoes',
            'casual shoes',
            'workout shoes',
            'running shoes',
            'sports shoes',
            'hiking shoes',
            'jewelry',
            'necklaces',
            'bracelets',
            'earrings',
            'rings',
            'watches',
            'anklets',
            'body jewelry',
            'brooches',
            'cufflinks',
            'tie pins',
            'hair accessories',
            'hats',
            'headbands',
            'hair clips',
            'hair ties',
            'hair bows',
            'cosmetics',
            'makeup',
            'foundation',
            'concealer',
            'powder',
            'blush',
            'highlighter',
            'eyeshadow',
            'eyeliner',
            'mascara',
            'lipstick',
            'lip gloss',
            'nail polish',
            'fragrances',
            'perfumes',
            'colognes',
            'body sprays',
            'deodorants',
            'skincare',
            'cleansers',
            'toners',
            'moisturizers',
            'serums',
            'face masks',
            'eye creams',
            'body lotions',
            'sunscreen',
            'bath and body',
            'body wash',
            'body scrub',
            'body butter',
            'shower gel',
            'hand cream',
            'foot cream',
            'nail care',
            'nail clippers',
            'nail files',
            'nail buffers',
            'nail polish remover',
            'intimate care',
            'feminine hygiene',
            'menstrual products',
            'bras',
            'panties',
            'shapewear',
            'Adidas',
            'H&M',
            'Zara',
            'Levi\'s',
            'Calvin Klein',
            'Tommy Hilfiger',
            'Gucci',
            'Prada',
            'Burberry',
            'Versace',
            'Chanel',
            'Dior',
            'Louis Vuitton',
            'Balenciaga',
            'Yves Saint Laurent',
            'Ralph Lauren',
            'Fendi',
            'Givenchy',
            'Valentino',
            'Hugo Boss',
            'Armani',
            'Diesel',
            'Puma',
            'Reebok',
            'Converse',
            'Vans',
            'The North Face',
            'Patagonia',
            'Columbia',
            'Under Armour',
            'Lululemon',
            'Gap',
            'Banana Republic',
            'J.Crew',
            'American Eagle',
            'Forever 21',
            'Old Navy',
            'Anthropologie',
            'Urban Outfitters',
            'Free People',
            'Madewell',
            'L.L.Bean',
            'Eddie Bauer',
            'Timberland',
            'Carhartt',
            'Wrangler',
            'Abercrombie & Fitch',
            'Hollister',
            'Victoria\'s Secret',
            'Aerie',
            'The Gap',
            'Aritzia',
            'Roots',
            'Canada Goose',
            'Lacoste',
            'Superdry',
            'ASOS',
            'Topshop',
            'River Island',
            'Primark',
            'Boohoo',
            'Next',
            'Mango',
            'Pull & Bear',
            'Stradivarius',
            'Bershka',
            'Oysho',
            'Massimo Dutti',
            'COS',
            'Weekday',
            'H&M Studio',
            '& Other Stories',
            'Monki',
            'Sandro',
            'Maje',
            'Zadig & Voltaire',
            'Comptoir des Cotonniers',
            'Uniqlo',
            'Muji',
            'Cosabella',
            'Hanky Panky',
            'Spanx',
            'La Perla',
            'Agent Provocateur',
            'Wolford',
        ]
    },
    {
        key: 'Home and Office',
        category: [
            'bedding',
            'bed sheets',
            'duvet covers',
            'comforters',
            'pillows',
            'mattress toppers',
            'blankets',
            'throws',
            'quilts',
            'bedspreads',
            'mattresses',
            'bed frames',
            'headboards',
            'nightstands',
            'dressers',
            'chests',
            'wardrobes',
            'armoires',
            'vanities',
            'bedroom sets',
            'sofas',
            'sectional sofas',
            'loveseats',
            'recliners',
            'accent chairs',
            'ottomans',
            'chaise lounges',
            'coffee tables',
            'end tables',
            'console tables',
            'TV stands',
            'entertainment centers',
            'bookcases',
            'shelving units',
            'cabinets',
            'dining tables',
            'dining chairs',
            'bar stools',
            'sideboards',
            'buffets',
            'china cabinets',
            'kitchen islands',
            'pantry cabinets',
            'benches',
            'desks',
            'office chairs',
            'file cabinets',
            'bookshelves',
            'desk organizers',
            'desk lamps',
            'desk accessories',
            'rugs',
            'area rugs',
            'runners',
            'outdoor rugs',
            'doormats',
            'carpets',
            'curtains',
            'drapes',
            'blinds',
            'shades',
            'window treatments',
            'curtain rods',
            'curtain hooks',
            'tiebacks',
            'blinds accessories',
            'shower curtains',
            'bathroom mats',
            'bath towels',
            'hand towels',
            'washcloths',
            'shower caddies',
            'shower dispensers',
            'toilet paper holders',
            'towel racks',
            'bathroom shelves',
            'bathroom storage',
            'bathroom mirrors',
            'vanity mirrors',
            'bathroom accessories',
            'bedroom decor',
            'living room decor',
            'dining room decor',
            'kitchen decor',
            'bathroom decor',
            'wall art',
            'paintings',
            'prints',
            'photographs',
            'wall sculptures',
            'wall decals',
            'mirrors',
            'clocks',
            'vases',
            'candles',
            'candle holders',
            'votive holders',
            'scented candles',
            'table lamps',
            'floor lamps',
            'chandeliers',
            'pendant lights',
            'ceiling lights',
            'string lights',
            'lamp shades',
            'fireplaces',
            'fireplace tools',
            'fireplace screens',
            'fireplace accessories',
            'indoor fountains',
            'throw pillows',
            'cushions',
            'throws',
            'afghans',
            'bean bags',
            'storage baskets',
            'storage bins',
            'storage boxes',
            'shoe racks',
            'laundry hampers',
            'laundry baskets',
            'closet organizers',
            'garment racks',
            'coatracks',
            'umbrella stands',
            'room dividers',
            'partitions',
            'window seats',
            'home',
            'office',
            'window benches',
            'window cushions',
            'window blinds',
            'window shades',
        ]
    }
]
