export const countryCurrency = [
  { abb: "AU", country: "Australia", currency: "AUD", symbol: "$" },
  { abb: "AT", country: "Austria", currency: "EUR", symbol: "€" },
  { abb: "BE", country: "Belgium", currency: "EUR", symbol: "€" },
  { abb: "BG", country: "Bulgaria", currency: "BGN", symbol: "лв" },
  { abb: "CA", country: "Canada", currency: "CAD", symbol: "$" },
  { abb: "HR", country: "Croatia", currency: "HRK", symbol: "kn" },
  { abb: "CY", country: "Cyprus", currency: "EUR", symbol: "€" },
  { abb: "CZ", country: "Czech", currency: "CZK", symbol: "Kč" },
  { abb: "DK", country: "Denmark", currency: "DKK", symbol: "kr" },
  { abb: "EE", country: "Estonia", currency: "EUR", symbol: "€" },
  { abb: "FI", country: "Finland", currency: "EUR", symbol: "€" },
  { abb: "FR", country: "France", currency: "EUR", symbol: "€" },
  { abb: "DE", country: "Germany", currency: "EUR", symbol: "€" },
  { abb: "GR", country: "Greece", currency: "EUR", symbol: "€" },
  { abb: "HU", country: "Hungary", currency: "HUF", symbol: "Ft" },
  { abb: "IE", country: "Ireland", currency: "EUR", symbol: "€" },
  { abb: "IT", country: "Italy", currency: "EUR", symbol: "€" },
  { abb: "LT", country: "Lithuania", currency: "EUR", symbol: "€" },
  { abb: "LU", country: "Luxembourg", currency: "EUR", symbol: "€" },
  { abb: "MX", country: "Mexico", currency: "MXN", symbol: "$" },
  { abb: "NL", country: "Netherlands", currency: "EUR", symbol: "€" },
  { abb: "NZ", country: "New Zealand", currency: "NZD", symbol: "$" },
  { abb: "NO", country: "Norway", currency: "NOK", symbol: "kr" },
  { abb: "PL", country: "Poland", currency: "PLN", symbol: "zł" },
  { abb: "PT", country: "Portugal", currency: "EUR", symbol: "€" },
  { abb: "ES", country: "Spain", currency: "EUR", symbol: "€" },
  { abb: "SE", country: "Sweden", currency: "SEK", symbol: "kr" },
  { abb: "CH", country: "Switzerland", currency: "CHF", symbol: "Fr" },
  { abb: "GB", country: "United Kingdom", currency: "Pounds", symbol: "£" },
  { abb: "US", country: "United States", currency: "USD", symbol: "$" },
];
